CREATE EXTERNAL TABLE `prod_speedtest4`(
  `session_id` string,
  `execution_id` string,
  `run_date` string,
  `ip_address` string,
  `account_id` string,
  `download_speed` string,
  `product_number` string,
  `csp_account` struct<
      account_id:string,
      `current`:boolean,
      id:string
  >,
  `xsp_device_swaps`
    struct<`raw_swaps_data`:struct<
      `output`:struct<
          `accountcontactdetails`:struct<
             `addressstate`:string,
              `addressstreet`:string,
              `city`:string,
              `email`:string,
              `firstname`:string,
              `lastname`:string,
              `phonenumber`:string,
              `zip`:string
          >,
        `accountnumber`:string,
        `customertype`:string,
        `devicedetails`:array<struct<
          `batterystatus`:string,
          `docsisversion`:string,
          `downspeed`:string,
          `eoldate`:string,
          `indicators`:array<string>,
          `macaddress`:string,
          `model`:string,
          `program`:array<struct<
              `eligibilitydate`:string,
              `name`:string
            >
          >,
          `serialnumber`:string,
          `type`:string,
          `upspeed`:string
        >
      >,
      `division`:string,
      `eligibility`:array<struct<
          `eol`:string,
          `leased`:string,
          `newdeviceactivationvalue`:string,
          `programname`:string,
          `swapeligibledevices`:string
        >
      >,
      `eligibilitystatus`:string,
      `fta`:string,
      `hdindicator`:string,
      `headendtype`:string,
      `indicators`:array<string>,
      `inflightorder`:string,
      `isemployee`:boolean,
      `optionaleligibility`:string,
      `region`:string,
      `sikeligible`:boolean,
      `swapeligibilitydate`:string,
      `swaptypes`:string,
      `wavenumber`:string
    >,
    `status`:string
  >,
  `swaps_are_active`:string,
  `swaps_eligibility`:string,
  `swaps_message`:string
  >,
  `csp_csp_outages`
    struct<`home`:struct<
      `outages`:array<struct<
        `description`:string,
        `enddatetime`:string,
        `enddatetimeinmillis`:int,
        `estimatedresolutiondatetime`:string,
        `estimatedresolutiondatetimeinmillis`:int, `id`:string, `linklabel`:string, `linkurl`:string, `outagetype`:string, `priority`:string, `startdatetime`:string, `startdatetimeinmillis`:int, `ticketnumber`:string, `title`:string>>>, `internet`:struct<`outages`:array<struct<`description`:string, `enddatetime`:string, `enddatetimeinmillis`:int, `estimatedresolutiondatetime`:string, `estimatedresolutiondatetimeinmillis`:int, `id`:string, `linklabel`:string, `linkurl`:string, `outagetype`:string, `priority`:string, `startdatetime`:string, `startdatetimeinmillis`:int, `ticketnumber`:string, `title`:string>>>, `status`:string, `statustime`:string, `statustimeinmillis`:double, `video`:struct<`outages`:array<struct<`description`:string, `enddatetime`:string, `enddatetimeinmillis`:int, `estimatedresolutiondatetime`:string, `estimatedresolutiondatetimeinmillis`:int, `id`:string, `linklabel`:string, `linkurl`:string, `outagetype`:string, `priority`:string, `startdatetime`:string, `startdatetimeinmillis`:int, `ticketnumber`:string, `title`:string>>>, `voice`:struct<`outages`:array<struct<`description`:string, `enddatetime`:string, `enddatetimeinmillis`:int, `estimatedresolutiondatetime`:string, `estimatedresolutiondatetimeinmillis`:int, `id`:string, `linklabel`:string, `linkurl`:string,
  `outagetype`:string, `priority`:string, `startdatetime`:string, `startdatetimeinmillis`:int, `ticketnumber`:string, `title`:string>>>>
  ,
  `csp_csp_gateway`
      struct<
        activationstatus:string,
        bridgemode:string,
        connecteddevices:string,
        createdate:string,
        firmware:string,
        friendlyname:string,
        gatewaytype:string,
        id:string,
        images:struct<
          mobileimagelarge:string,
          webimagelarge:string,
          x2imagelarge:string
        >,
        mac:string,
        make:string,
        odel:string,
        responsestatus:struct<
        si:struct<
            responsestatus:string,
            status:string
        >
      >,
      serialnumber:string,
      sienabled:boolean,
      wifiextenders:string,
      wifinetworks:string,
      wifivalidation:string>,
  `csp_csp_internet_service_details`
      struct<
        tier:struct<
          downloadspeed:double,
          productnumber:string,
          tierofservice:string,
          uploadspeed:double
        >
    >,
 `speedtest-web_wurfl` struct<
      `advertised_browser`:string,
      `advertised_browser_version`:string,
      `advertised_device_os`:string,
      `advertised_device_os_version`:string,
      `brand_name`:string,
      `complete_device_name`:string,
      `form_factor`:string,
      `is_app_webview`:boolean,
      `is_full_desktop`:boolean,
      `is_mobile`:boolean,
      `is_robot`:boolean,
      `is_smartphone`:boolean,
      `is_smarttv`:boolean,
      `is_tablet`:boolean,
      `manufacturer_name`:string,
      `marketing_name`:string,
      `max_image_height`:double,
      `max_image_width`:double,
      `model_name`:string,
      `physical_screen_height`:double,
      `physical_screen_width`:double,
      `pointing_method`:string,
      `resolution_height`:double,
      `resolution_width`:double
   >,
    `speedtest-rdkb` array<struct<
          `client_ipv4_address`:string,
          `client_ipv6_address`:string,
          `cm_mac`:string,
          `download_offset`:int,
          `duration`:int,
          `error`:int,
          `firmware_version`:string,
          `iperf_version`:string,
          `ipv4_download_bytes`:int,
          `ipv4_download_cal_kbps`:double,
          `ipv4_download_client_cpu_util`:double,
          `ipv4_download_duration`:double,
          `ipv4_download_kbps`:double,
          `ipv4_download_total_bytes`:int,
          `ipv4_latency`:int,
          `ipv4_upload_bytes`:int,
          `ipv4_upload_cal_kbps`:double,
          `ipv4_upload_client_cpu_util`:double,
          `ipv4_upload_duration`:double,
          `ipv4_upload_kbps`:double,
          `ipv6`:int,
          `market`:string,
          `mw_app_version`:string,
          `prov_speed_dn`:int,
          `prov_speed_up`:int,
          `result_id`:int,
          `server_id`:int,
          `server_port`:int,
          `server_result_date`:string,
          `speedtest_elapsed_time`:int,
          `stats_cpu_usage`:double,
          `stats_download_kbps`:double,
          `stats_upload_kbps`:double,
          `threads`:int,
          `ubb_download_byte_count`:int,
          `ubb_upload_byte_count`:int,
          `upload_offset`:int,
          `user_agent`:string,
          `uuid`:string
        >
    >,
    `speedtest-web` array<struct<
    `accountname`:string,
    `browser_name`:string,
    `browser_version`:string,
    `cima_logged_in`:boolean,
    `cima_username`:string,
    `client_ipv4_address`:string,
    `client_ipv6_address`:string,
    `client_isp`:string,
    `client_latitude`:string,
    `client_longitude`:string,
    `default_server_id`:double,
    `division`:string,
    `ipv4_download_mbps`:string,
    `ipv4_download_peak`:string,
    `ipv4_latency`:string,
    `ipv4_upload_mbps`:string,
    `ipv4_upload_peak`:string,
    `ipv4downloaddata`:string,
    `ipv4uploaddata`:string,
    `ipv6`:double,
    `ipv6_download_mbps`:string,
    `ipv6_download_peak`:string,
    `ipv6_latency`:double,
    `ipv6_upload_mbps`:string,
    `ipv6_upload_peak`:string,
    `ipv6downloaddata`:string,
    `ipv6uploaddata`:string,
    `market`:string,
    `operative_system`:string,
    `platform`:string,
    `region`:string,
    `result_date`:string,
    `server_hostname`:string,
    `server_name`:string,
    `server_sitename`:string,
    `supportwebsocket`:boolean,
    `test_method`:string
  >>,
 `ptdb_ptdb_gateway` struct<
    `alias`:string,
    `base_created_by`:string,
    `base_import_state`:string,
    `base_stamp_created`:string,
    `base_stamp_updated`:string,
    `comment`:string,
    `cpe_name`:string,
    `created_by`:string,
    `deployment_model_base_id`:string,
    `deployment_model_base_list`:string,
    `deployment_model_id`:string,
    `deployment_model_list`:string,
    `deployment_network_type`:string,
    `deployment_software_type`:string,
    `device_class`:string,
    `device_id`:string,
    `device_type`:string,
    `import_state`:string,
    `lifecycle`:string,
    `lifecycle_date`:string,
    `manufacturer`:string,
    `model`:string,
    `ownership`:string,
    `spec_milestone`:string,
    `stamp_created`:string,
    `stamp_updated`:string
  >,
   `https://odp-prod.codebig2.net/api/v1/operational/gateway-cpe/fc911453ae4e/devices/summary` struct<
      `data`:array<struct<
            `connection_interface`:string,
            `device_mac`:string,
            `device_parent`:string,
            `device_type`:string,
            `device_uuid`:string,
            `fingerprint_data`:struct<
                `device_brand`:string,
                `device_model`:string,
                `device_type`:string,
                `dhcp_hostname`:string,
                `is_4k_device`:boolean,
                `is_streaming_device`:boolean,
                `model_accuracy_level`:double,
                `operating_system`:string>,
                `hostname`:string,
                `ip_address`:string,
                `is_active`:boolean,
                `last_seen_offline_time`:double,
                `last_seen_online_time`:double,
                `manufacturer`:string,
                `service_type`:string
              >
            >,
            `host_table_version`:double,
            `last_summary_report_cpe_timestamp`:double,
            `last_summary_report_timestamp`:double,
            `message`:string,
            `source`:string,
            `status`:double
    >,
   `https://odp-prod.codebig2.net/api/v1/operational/gateway-cpe/fc911453ae4e/devices/interface_data/latest` struct<
      `cpe_status`:string,
      `data`:array<struct<
          `device_mac`:string,
          `interface_mac`:string,
          `interface_type`:string,
          `phy_rx_rate`:double,
          `phy_tx_rate`:double,
          `radio_channel`:double,
          `rssi`:double,
          `service_type`:string,
          `ssid`:string,
          `time_stamp`:double,
          `wifi_channel_bandwidth`:string,
          `wifi_operating_standard`:string
        >
      >,
      `last_interface_report_cpe_timestamp`:double,
      `last_interface_report_timestamp`:double,
      `message`:string,
      `status`:double
      >

  )
ROW FORMAT SERDE
  'org.openx.data.jsonserde.JsonSerDe'
WITH SERDEPROPERTIES (
  'ignore.malformed.json'='true')
LOCATION
  's3://ipie-prod-analytics/2018'
